// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosqueLife.Server.Data.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MosqueLife.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211210173821_AddPaymentNote")]
    partial class AddPaymentNote
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MosqueLife.Server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MosqueLife.Server.Data.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ecaafbc-af46-4a7c-a9dc-6bb7096f8929"),
                            Alpha2Code = "AF",
                            Alpha3Code = "AFG",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("a33a5b08-d624-49b3-b451-8d371deef429"),
                            Alpha2Code = "AL",
                            Alpha3Code = "ALB",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("ef7bc59d-1c60-4cce-b78e-77447839e181"),
                            Alpha2Code = "DZ",
                            Alpha3Code = "DZA",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("ac38b0f1-134e-41a9-b361-a5012e8e3d3c"),
                            Alpha2Code = "AS",
                            Alpha3Code = "ASM",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = new Guid("0af6985e-b3a8-4225-afbe-42e7e5e9e26b"),
                            Alpha2Code = "AD",
                            Alpha3Code = "AND",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("cf48f7ca-042f-4a25-81c2-4b48332a7f5a"),
                            Alpha2Code = "AO",
                            Alpha3Code = "AGO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("011b06b2-3aa8-4047-9e52-47c0ef010e4d"),
                            Alpha2Code = "AI",
                            Alpha3Code = "AIA",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = new Guid("f89b51b9-a6e5-41de-aa3c-77614e91f52e"),
                            Alpha2Code = "AQ",
                            Alpha3Code = "ATA",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = new Guid("6fcffd3e-ac9a-4abd-a44b-b13a5558d743"),
                            Alpha2Code = "AG",
                            Alpha3Code = "ATG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("2f7371e6-33bc-4939-9735-034aa10f6ac9"),
                            Alpha2Code = "AR",
                            Alpha3Code = "ARG",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("37a4d8f9-6ce1-4611-a540-4b54f936c973"),
                            Alpha2Code = "AM",
                            Alpha3Code = "ARM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("753d5556-64e7-46cd-bc97-2fa50d0970c2"),
                            Alpha2Code = "AW",
                            Alpha3Code = "ABW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("d4a71bbc-eeb2-4693-bc96-25372ccb7929"),
                            Alpha2Code = "AU",
                            Alpha3Code = "AUS",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("08c2fc07-b083-4ce7-8a28-e180ebf2326b"),
                            Alpha2Code = "AT",
                            Alpha3Code = "AUT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("9f04b793-305a-453e-bc51-1749104536d9"),
                            Alpha2Code = "AZ",
                            Alpha3Code = "AZE",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("ffd997c4-6cec-4993-8edd-0376784d8973"),
                            Alpha2Code = "BS",
                            Alpha3Code = "BHS",
                            Name = "Bahamas (the)"
                        },
                        new
                        {
                            Id = new Guid("0841c778-23cb-4ea4-bb5b-950f3d4d2c10"),
                            Alpha2Code = "BH",
                            Alpha3Code = "BHR",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("7b56a3a2-d433-4432-a3af-5c3c1872103c"),
                            Alpha2Code = "BD",
                            Alpha3Code = "BGD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("1ef58b86-ffb9-4e6d-8641-8bdb6bc2e51a"),
                            Alpha2Code = "BB",
                            Alpha3Code = "BRB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("a70721d4-6426-4eee-a60f-95fca983cf28"),
                            Alpha2Code = "BY",
                            Alpha3Code = "BLR",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("59532a0f-0c95-40c5-a1f5-fffb589540f5"),
                            Alpha2Code = "BE",
                            Alpha3Code = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("fd5dba2a-999b-4720-a0a6-d87f39cdd9b3"),
                            Alpha2Code = "BZ",
                            Alpha3Code = "BLZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("1b253905-4292-4941-9efb-f8e28762ebe1"),
                            Alpha2Code = "BJ",
                            Alpha3Code = "BEN",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("9744a74d-3c85-4c15-a23b-514580aaf41f"),
                            Alpha2Code = "BM",
                            Alpha3Code = "BMU",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = new Guid("d434e065-5c31-4881-bef3-b53d8adb20ce"),
                            Alpha2Code = "BT",
                            Alpha3Code = "BTN",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("653a5814-e9ba-4afa-97c6-3856023e2a86"),
                            Alpha2Code = "BO",
                            Alpha3Code = "BOL",
                            Name = "Bolivia (Plurinational State of)"
                        },
                        new
                        {
                            Id = new Guid("f1b3c5c2-ad82-440d-aff2-71647f75e400"),
                            Alpha2Code = "BQ",
                            Alpha3Code = "BES",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = new Guid("20ea933e-023a-4e5b-997e-b9bad3e54cd2"),
                            Alpha2Code = "BA",
                            Alpha3Code = "BIH",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("7bdbabda-d487-4ec9-89b1-015a3c5e9391"),
                            Alpha2Code = "BW",
                            Alpha3Code = "BWA",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("284dca74-da6d-4228-9df8-5b2f5a344057"),
                            Alpha2Code = "BV",
                            Alpha3Code = "BVT",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = new Guid("55024a10-cfe0-472e-8f2f-748a1f960bf5"),
                            Alpha2Code = "BR",
                            Alpha3Code = "BRA",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("94035b74-9598-4912-b9d4-48f7fbc6120a"),
                            Alpha2Code = "IO",
                            Alpha3Code = "IOT",
                            Name = "British Indian Ocean Territory (the)"
                        },
                        new
                        {
                            Id = new Guid("30ebf3fe-ebf9-49a5-96cf-9b709a72bc4d"),
                            Alpha2Code = "BN",
                            Alpha3Code = "BRN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = new Guid("9d5d0da6-c7a0-4cb1-bdaa-35fae9616974"),
                            Alpha2Code = "BG",
                            Alpha3Code = "BGR",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("555f9d6e-6dd3-477d-8f6a-1131c153e061"),
                            Alpha2Code = "BF",
                            Alpha3Code = "BFA",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("1dedcb63-8bcc-4bd9-a725-93cbc0a4644e"),
                            Alpha2Code = "BI",
                            Alpha3Code = "BDI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("2da08c51-ec1c-4896-b349-5b0d8ca66039"),
                            Alpha2Code = "CV",
                            Alpha3Code = "CPV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = new Guid("96c04e08-db94-4e58-aa3c-7a4b59c31da9"),
                            Alpha2Code = "KH",
                            Alpha3Code = "KHM",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("9d937d08-5fab-4689-8622-3b260d1d9a0f"),
                            Alpha2Code = "CM",
                            Alpha3Code = "CMR",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("3f95334f-14c0-437b-b7d4-eb5b7023faf2"),
                            Alpha2Code = "CA",
                            Alpha3Code = "CAN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("5a5d00ef-026f-481a-a7c4-b05870e84c88"),
                            Alpha2Code = "KY",
                            Alpha3Code = "CYM",
                            Name = "Cayman Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("8d4c6695-ceae-4f48-b6a9-39be1ee88cf4"),
                            Alpha2Code = "CF",
                            Alpha3Code = "CAF",
                            Name = "Central African Republic (the)"
                        },
                        new
                        {
                            Id = new Guid("3a991f3a-939a-49bf-876d-cf19db30ff14"),
                            Alpha2Code = "TD",
                            Alpha3Code = "TCD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("6f4a774f-863f-4e09-b8d8-3b22cdca5deb"),
                            Alpha2Code = "CL",
                            Alpha3Code = "CHL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("2bb4ea20-5db8-4d0e-a398-f6eed7db833c"),
                            Alpha2Code = "CN",
                            Alpha3Code = "CHN",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("b3639d78-54dc-4fe0-989c-a8d08ab8093d"),
                            Alpha2Code = "CX",
                            Alpha3Code = "CXR",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = new Guid("b34073c8-5ee0-4990-a7cc-6aacb209b0d3"),
                            Alpha2Code = "CC",
                            Alpha3Code = "CCK",
                            Name = "Cocos (Keeling) Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("ec485b6a-4a69-40d6-a34e-559c0b25f96c"),
                            Alpha2Code = "CO",
                            Alpha3Code = "COL",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("85cc67ab-22ec-4ef5-84b8-22490145eda5"),
                            Alpha2Code = "KM",
                            Alpha3Code = "COM",
                            Name = "Comoros (the)"
                        },
                        new
                        {
                            Id = new Guid("bba74714-4497-4806-bad9-e74075217ca2"),
                            Alpha2Code = "CD",
                            Alpha3Code = "COD",
                            Name = "Congo (the Democratic Republic of the)"
                        },
                        new
                        {
                            Id = new Guid("c70a2df5-fd2a-4a99-9b98-7254ada8460c"),
                            Alpha2Code = "CG",
                            Alpha3Code = "COG",
                            Name = "Congo (the)"
                        },
                        new
                        {
                            Id = new Guid("1d8a0fe1-7f8f-4fa9-a336-8902b8b27a9e"),
                            Alpha2Code = "CK",
                            Alpha3Code = "COK",
                            Name = "Cook Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("4f5a6bb2-55f4-4cbc-9149-61d49b14ac9d"),
                            Alpha2Code = "CR",
                            Alpha3Code = "CRI",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("f48fcde0-a6bb-4668-b8bf-92d028ca9ab3"),
                            Alpha2Code = "HR",
                            Alpha3Code = "HRV",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("ed97b7e9-06b1-40ed-bae4-c14e301d5042"),
                            Alpha2Code = "CU",
                            Alpha3Code = "CUB",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("9f10a9d9-3823-466c-beb6-dd7543100b80"),
                            Alpha2Code = "CW",
                            Alpha3Code = "CUW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = new Guid("fb561aec-6c55-4d51-9537-05facbd91dda"),
                            Alpha2Code = "CY",
                            Alpha3Code = "CYP",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("f293b8ea-529e-4c90-8044-7f37717e8980"),
                            Alpha2Code = "CZ",
                            Alpha3Code = "CZE",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = new Guid("317160b1-4cb7-45b8-8e54-e98c2373466e"),
                            Alpha2Code = "CI",
                            Alpha3Code = "CIV",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = new Guid("d69602bd-76f3-4785-a498-3874cbaa970f"),
                            Alpha2Code = "DK",
                            Alpha3Code = "DNK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("54d14be5-6a0b-4817-928d-3b63c2fcffa6"),
                            Alpha2Code = "DJ",
                            Alpha3Code = "DJI",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("cb9ec68e-1006-4525-8612-44329c816757"),
                            Alpha2Code = "DM",
                            Alpha3Code = "DMA",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("60ab754a-4df0-4254-a9bc-3714a25f9764"),
                            Alpha2Code = "DO",
                            Alpha3Code = "DOM",
                            Name = "Dominican Republic (the)"
                        },
                        new
                        {
                            Id = new Guid("e2b629b1-bbc6-4d34-8b3c-35f7524cdd54"),
                            Alpha2Code = "EC",
                            Alpha3Code = "ECU",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("94918806-4e2c-41eb-b3db-19d0c43c4280"),
                            Alpha2Code = "EG",
                            Alpha3Code = "EGY",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("ef8601c1-4735-4350-a359-5b1ebe597e0d"),
                            Alpha2Code = "SV",
                            Alpha3Code = "SLV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("9a8ad1d0-4c5b-489f-9ef3-0774bc698943"),
                            Alpha2Code = "GQ",
                            Alpha3Code = "GNQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("a18ae9ac-ed68-4b3e-85a5-037a0dac5cf6"),
                            Alpha2Code = "ER",
                            Alpha3Code = "ERI",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("27265d25-3b49-4ee7-9fe7-3ba41f094e16"),
                            Alpha2Code = "EE",
                            Alpha3Code = "EST",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("2d0b5d27-c0cc-4e37-bcc8-365467f8022c"),
                            Alpha2Code = "SZ",
                            Alpha3Code = "SWZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("2bd96788-8ae4-494e-8637-ba347f2bbbca"),
                            Alpha2Code = "ET",
                            Alpha3Code = "ETH",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("6470d150-c33c-49e2-b0e9-4dbb9574aedb"),
                            Alpha2Code = "FK",
                            Alpha3Code = "FLK",
                            Name = "Falkland Islands (the) [Malvinas]"
                        },
                        new
                        {
                            Id = new Guid("e55c2bf2-266d-4af5-953a-d5cdb52e9073"),
                            Alpha2Code = "FO",
                            Alpha3Code = "FRO",
                            Name = "Faroe Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("3713bbb1-1b45-43d0-851e-cce44e894f05"),
                            Alpha2Code = "FJ",
                            Alpha3Code = "FJI",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("12df6980-409d-4129-b6f3-d71d1ce8087a"),
                            Alpha2Code = "FI",
                            Alpha3Code = "FIN",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("d761bb47-8477-4f67-a992-2535c789f30f"),
                            Alpha2Code = "FR",
                            Alpha3Code = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("6faffedf-4a24-4a05-a7e3-36f10d3a6c1c"),
                            Alpha2Code = "GF",
                            Alpha3Code = "GUF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = new Guid("49b07547-6593-4a59-a296-9ae4322adca3"),
                            Alpha2Code = "PF",
                            Alpha3Code = "PYF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = new Guid("90b599dc-4581-406b-8b8e-589b72e6bb9f"),
                            Alpha2Code = "TF",
                            Alpha3Code = "ATF",
                            Name = "French Southern Territories (the)"
                        },
                        new
                        {
                            Id = new Guid("c4a41ca2-1f47-4ec3-b250-0942e31603cc"),
                            Alpha2Code = "GA",
                            Alpha3Code = "GAB",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("994d9d8e-ded2-4355-bb0f-f3a66a3a4779"),
                            Alpha2Code = "GM",
                            Alpha3Code = "GMB",
                            Name = "Gambia (the)"
                        },
                        new
                        {
                            Id = new Guid("d10ff280-01b1-4ad0-b1fa-992b9dad9b53"),
                            Alpha2Code = "GE",
                            Alpha3Code = "GEO",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("80f6fadb-c0e0-41eb-bfdf-c253c3c2945b"),
                            Alpha2Code = "DE",
                            Alpha3Code = "DEU",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("c43bf101-d151-406f-8669-cc6e2ad0dba2"),
                            Alpha2Code = "GH",
                            Alpha3Code = "GHA",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("2d235488-6cff-4a90-a2bd-2d259933fe1b"),
                            Alpha2Code = "GI",
                            Alpha3Code = "GIB",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = new Guid("74eea3e2-7f1b-4c0c-b63c-7bc1c4fa8670"),
                            Alpha2Code = "GR",
                            Alpha3Code = "GRC",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("b89d7b1a-27c3-4859-aa7e-23293f4b9ca0"),
                            Alpha2Code = "GL",
                            Alpha3Code = "GRL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = new Guid("bff539e0-82c8-4a20-8c0b-567561a2646b"),
                            Alpha2Code = "GD",
                            Alpha3Code = "GRD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("f1526d84-2265-407a-97ba-15e4fb61ef3f"),
                            Alpha2Code = "GP",
                            Alpha3Code = "GLP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = new Guid("c5d646f9-009b-4d1b-b5fc-eb30a03e4b81"),
                            Alpha2Code = "GU",
                            Alpha3Code = "GUM",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = new Guid("543b391b-a9fc-4e71-96a8-7cf94c4f4d5b"),
                            Alpha2Code = "GT",
                            Alpha3Code = "GTM",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("f3ccee21-77d5-4bc6-a05a-2383710f5477"),
                            Alpha2Code = "GG",
                            Alpha3Code = "GGY",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = new Guid("9b94c3a2-2a0a-4ad0-b390-f414ac45e059"),
                            Alpha2Code = "GN",
                            Alpha3Code = "GIN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("d1dbe9ef-e4e0-44fd-a8f6-2a9b0b130a27"),
                            Alpha2Code = "GW",
                            Alpha3Code = "GNB",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("7b8484e1-0a41-466c-9903-1328e8669d1b"),
                            Alpha2Code = "GY",
                            Alpha3Code = "GUY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("883ac320-106d-4749-b225-87714d705763"),
                            Alpha2Code = "HT",
                            Alpha3Code = "HTI",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("35a040fc-1049-4938-ae12-8089ff3cfe85"),
                            Alpha2Code = "HM",
                            Alpha3Code = "HMD",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = new Guid("7a5a29fb-3171-4778-bb68-ede54e169111"),
                            Alpha2Code = "VA",
                            Alpha3Code = "VAT",
                            Name = "Holy See (the)"
                        },
                        new
                        {
                            Id = new Guid("fddff3c1-3bb3-4ee6-b9cc-628c3d53defb"),
                            Alpha2Code = "HN",
                            Alpha3Code = "HND",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("719281fe-c79f-43a2-b31b-23c928faa8e6"),
                            Alpha2Code = "HK",
                            Alpha3Code = "HKG",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("d8831f86-bd62-49c3-8805-b5c881acefa8"),
                            Alpha2Code = "HU",
                            Alpha3Code = "HUN",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("15f4c5e9-24bc-494c-92d5-cb3e976fe1f5"),
                            Alpha2Code = "IS",
                            Alpha3Code = "ISL",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("7f0ecd37-0e96-4271-b975-ffc72ef86cc4"),
                            Alpha2Code = "IN",
                            Alpha3Code = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("b9b8535e-1e6b-4e39-a6ac-1b7e57bfd33c"),
                            Alpha2Code = "ID",
                            Alpha3Code = "IDN",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("7bf2c229-1165-4587-bcf8-cfd0b4952879"),
                            Alpha2Code = "IR",
                            Alpha3Code = "IRN",
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = new Guid("5e6def8e-12af-415e-9cb9-276f97914bf0"),
                            Alpha2Code = "IQ",
                            Alpha3Code = "IRQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("a39279d9-e93f-4a22-abb7-6cc05e5e8874"),
                            Alpha2Code = "IE",
                            Alpha3Code = "IRL",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("908765e7-efe7-4c56-81ac-bb2c86bcc093"),
                            Alpha2Code = "IM",
                            Alpha3Code = "IMN",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = new Guid("bdb15a05-6afc-413d-867c-47a87c2e0074"),
                            Alpha2Code = "IL",
                            Alpha3Code = "ISR",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("d0958301-d073-4252-a183-0a2b34afcc94"),
                            Alpha2Code = "IT",
                            Alpha3Code = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("a5f125cb-e6a2-409b-af94-54c9284204f9"),
                            Alpha2Code = "JM",
                            Alpha3Code = "JAM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("d4993250-cdb6-40da-9474-48a97971307e"),
                            Alpha2Code = "JP",
                            Alpha3Code = "JPN",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("2979bb6d-2002-4abd-8785-e34dce26cfaf"),
                            Alpha2Code = "JE",
                            Alpha3Code = "JEY",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = new Guid("1192eb08-3026-480c-b21b-f62f6ec59f50"),
                            Alpha2Code = "JO",
                            Alpha3Code = "JOR",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("52a225d1-fac4-408a-9b82-e3c411f6d0d5"),
                            Alpha2Code = "KZ",
                            Alpha3Code = "KAZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("316b9969-ce67-4aa3-8476-7adc52407150"),
                            Alpha2Code = "KE",
                            Alpha3Code = "KEN",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("6a223637-18e4-4822-9c62-ba483a333d15"),
                            Alpha2Code = "KI",
                            Alpha3Code = "KIR",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("cdea498d-1b3f-4975-af1b-2e0ec2f3cafd"),
                            Alpha2Code = "KP",
                            Alpha3Code = "PRK",
                            Name = "Korea (the Democratic People's Republic of)"
                        },
                        new
                        {
                            Id = new Guid("aca267be-8365-4b73-a806-3cb547d5a211"),
                            Alpha2Code = "KR",
                            Alpha3Code = "KOR",
                            Name = "Korea (the Republic of)"
                        },
                        new
                        {
                            Id = new Guid("1a270b09-036d-4872-992e-88c357433e50"),
                            Alpha2Code = "KW",
                            Alpha3Code = "KWT",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("7ee68a9a-ad8d-4392-8146-7f393f85b7ed"),
                            Alpha2Code = "KG",
                            Alpha3Code = "KGZ",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("8596e8dc-49e8-4bae-b459-a73c9caa3767"),
                            Alpha2Code = "LA",
                            Alpha3Code = "LAO",
                            Name = "Lao People's Democratic Republic (the)"
                        },
                        new
                        {
                            Id = new Guid("569f984c-be17-4c77-83ea-a0d5a43d1d5e"),
                            Alpha2Code = "LV",
                            Alpha3Code = "LVA",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("e8235f90-9d31-4c9d-b7cc-8e7397057380"),
                            Alpha2Code = "LB",
                            Alpha3Code = "LBN",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("91a80287-a0f5-4de1-a10f-bf3a058f2b1c"),
                            Alpha2Code = "LS",
                            Alpha3Code = "LSO",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("cc5ec694-7ce2-4883-8dab-05a6f148243b"),
                            Alpha2Code = "LR",
                            Alpha3Code = "LBR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("b15897b7-cb1c-4da2-b2f8-d3d7af5b3ad0"),
                            Alpha2Code = "LY",
                            Alpha3Code = "LBY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("9fbb50fe-ff23-4abc-b524-2ed8d8b64a9b"),
                            Alpha2Code = "LI",
                            Alpha3Code = "LIE",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("8da1077a-231d-49d8-ae2d-8c0184eafea0"),
                            Alpha2Code = "LT",
                            Alpha3Code = "LTU",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("4e24c555-a619-48f1-afcd-7f8e536eacc1"),
                            Alpha2Code = "LU",
                            Alpha3Code = "LUX",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("f1357ee3-156c-41fe-9715-2c6929590fc2"),
                            Alpha2Code = "MO",
                            Alpha3Code = "MAC",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = new Guid("6e4c0de6-a8ac-481b-8e24-023d9e024c00"),
                            Alpha2Code = "MG",
                            Alpha3Code = "MDG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("6453c40a-f697-4223-9797-821ad45c4647"),
                            Alpha2Code = "MW",
                            Alpha3Code = "MWI",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("81b25266-fa29-4280-a30e-59f6d42f3f15"),
                            Alpha2Code = "MY",
                            Alpha3Code = "MYS",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("7a56db1d-0e7e-4932-9747-3f19a79f6534"),
                            Alpha2Code = "MV",
                            Alpha3Code = "MDV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("6618a417-5c7d-4e24-a77d-ccfe89ec38bf"),
                            Alpha2Code = "ML",
                            Alpha3Code = "MLI",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("6aa14e79-4d9a-4841-b412-367c778548b4"),
                            Alpha2Code = "MT",
                            Alpha3Code = "MLT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("20e1b116-df2d-4121-be5d-0c9814248ad2"),
                            Alpha2Code = "MH",
                            Alpha3Code = "MHL",
                            Name = "Marshall Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("aba79b10-e3d8-41b4-95ed-cb173b0d73e7"),
                            Alpha2Code = "MQ",
                            Alpha3Code = "MTQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = new Guid("147b82eb-c081-41dd-b87b-635d5c5054f3"),
                            Alpha2Code = "MR",
                            Alpha3Code = "MRT",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("6c8ab378-ddfe-4071-9f02-2cab31174dfd"),
                            Alpha2Code = "MU",
                            Alpha3Code = "MUS",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("7d810385-a431-4f6e-b1ed-abec8ecef91a"),
                            Alpha2Code = "YT",
                            Alpha3Code = "MYT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = new Guid("e8929799-dff3-443c-a417-e1871ca29c90"),
                            Alpha2Code = "MX",
                            Alpha3Code = "MEX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("983d6ec3-d9f5-4e19-a58b-efdd4d3609a7"),
                            Alpha2Code = "FM",
                            Alpha3Code = "FSM",
                            Name = "Micronesia (Federated States of)"
                        },
                        new
                        {
                            Id = new Guid("5aeb9baf-0198-4f2b-8183-a1ca51f66d96"),
                            Alpha2Code = "MD",
                            Alpha3Code = "MDA",
                            Name = "Moldova (the Republic of)"
                        },
                        new
                        {
                            Id = new Guid("3b63854e-07d3-4883-b997-d8a7496b0d45"),
                            Alpha2Code = "MC",
                            Alpha3Code = "MCO",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("a49834f0-4e9e-4402-bac5-e22d04dc3767"),
                            Alpha2Code = "MN",
                            Alpha3Code = "MNG",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("f66585ce-7b53-4b9b-8122-150f8a1bdb75"),
                            Alpha2Code = "ME",
                            Alpha3Code = "MNE",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("f6ee2169-65a5-4c0c-8ebc-eef7adf29481"),
                            Alpha2Code = "MS",
                            Alpha3Code = "MSR",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = new Guid("9596570c-3ed0-4a92-9ff5-8db594c072b0"),
                            Alpha2Code = "MA",
                            Alpha3Code = "MAR",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("08b97c4b-ba5c-496c-a77f-5394f483ab9e"),
                            Alpha2Code = "MZ",
                            Alpha3Code = "MOZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("60920235-7b02-43b0-a0a9-d7a509c6cd33"),
                            Alpha2Code = "MM",
                            Alpha3Code = "MMR",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("1ce59e25-dd93-46b3-8425-3392cb35151f"),
                            Alpha2Code = "NA",
                            Alpha3Code = "NAM",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("9832f4a3-ed3e-4aaf-a20c-457f4a26bd62"),
                            Alpha2Code = "NR",
                            Alpha3Code = "NRU",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("66ee8fd1-1ee5-4354-af86-30edc54fda19"),
                            Alpha2Code = "NP",
                            Alpha3Code = "NPL",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("c1eb37b8-e284-4c73-a6af-3b52dab81c39"),
                            Alpha2Code = "NL",
                            Alpha3Code = "NLD",
                            Name = "Netherlands (the)"
                        },
                        new
                        {
                            Id = new Guid("dc04de6a-e250-44f5-9299-f9f23eccd3ce"),
                            Alpha2Code = "NC",
                            Alpha3Code = "NCL",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = new Guid("59ed5d69-0838-4454-8186-629fc1621b93"),
                            Alpha2Code = "NZ",
                            Alpha3Code = "NZL",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("8eaa9550-1236-401a-ae24-810c8851ea5e"),
                            Alpha2Code = "NI",
                            Alpha3Code = "NIC",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("0889760b-4a1d-4163-8184-9062d56e4d8c"),
                            Alpha2Code = "NE",
                            Alpha3Code = "NER",
                            Name = "Niger (the)"
                        },
                        new
                        {
                            Id = new Guid("a7efd015-4c3e-493c-bc62-10a7bf762825"),
                            Alpha2Code = "NG",
                            Alpha3Code = "NGA",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("ee3e97c3-e3b9-49e8-9abb-3092669fd314"),
                            Alpha2Code = "NU",
                            Alpha3Code = "NIU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = new Guid("9514391e-4097-4a2e-9bab-9c18d083c26d"),
                            Alpha2Code = "NF",
                            Alpha3Code = "NFK",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = new Guid("2e8acc4a-bea1-4864-b197-a63233e8c397"),
                            Alpha2Code = "MP",
                            Alpha3Code = "MNP",
                            Name = "Northern Mariana Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("331aafed-3986-4275-b747-e2a79b1fe134"),
                            Alpha2Code = "NO",
                            Alpha3Code = "NOR",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("fc6da1c1-3236-455d-8f4c-9dbc9f5214c7"),
                            Alpha2Code = "OM",
                            Alpha3Code = "OMN",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("b16a98b9-9b6f-4db0-94b1-5cfc0718f2bd"),
                            Alpha2Code = "PK",
                            Alpha3Code = "PAK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("afbd6ead-3e62-4507-991e-2053f28f9278"),
                            Alpha2Code = "PW",
                            Alpha3Code = "PLW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("9d6cb9ec-760b-417e-9b72-8addbec15624"),
                            Alpha2Code = "PS",
                            Alpha3Code = "PSE",
                            Name = "Palestine, State of"
                        },
                        new
                        {
                            Id = new Guid("2b9dae73-d40c-4f48-94e1-c00f3b963c1d"),
                            Alpha2Code = "PA",
                            Alpha3Code = "PAN",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("d58e62c1-78af-4307-9aea-be667612c4c4"),
                            Alpha2Code = "PG",
                            Alpha3Code = "PNG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("80a1cb0a-d12c-4418-9422-49b497c64a45"),
                            Alpha2Code = "PY",
                            Alpha3Code = "PRY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("8d82e03f-3a66-46e1-abf4-1c03e9554236"),
                            Alpha2Code = "PE",
                            Alpha3Code = "PER",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("edad8646-82cc-4137-9519-18034b1f6dea"),
                            Alpha2Code = "PH",
                            Alpha3Code = "PHL",
                            Name = "Philippines (the)"
                        },
                        new
                        {
                            Id = new Guid("e3dd51f1-acbf-4fe9-bd53-4aa8b59d425d"),
                            Alpha2Code = "PN",
                            Alpha3Code = "PCN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = new Guid("549fba38-4427-4c65-9071-800e0afd84dc"),
                            Alpha2Code = "PL",
                            Alpha3Code = "POL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("f6422962-2b04-4470-a3c7-7bb55a7a2d45"),
                            Alpha2Code = "PT",
                            Alpha3Code = "PRT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("ed14ef85-515a-4f7c-a001-76aec44ebe59"),
                            Alpha2Code = "PR",
                            Alpha3Code = "PRI",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = new Guid("b9939a38-eab5-4d8f-906a-e2b2c5f7da55"),
                            Alpha2Code = "QA",
                            Alpha3Code = "QAT",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("ed1149bc-0dfb-4746-b800-655809739578"),
                            Alpha2Code = "MK",
                            Alpha3Code = "MKD",
                            Name = "Republic of North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("f1a94128-3d8d-473c-baa2-1e9c0b971cdb"),
                            Alpha2Code = "RO",
                            Alpha3Code = "ROU",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("a731ed1b-eed0-4b67-b1fd-f9e7625d0f7e"),
                            Alpha2Code = "RU",
                            Alpha3Code = "RUS",
                            Name = "Russian Federation (the)"
                        },
                        new
                        {
                            Id = new Guid("23c66a5d-a9f5-4a50-bde4-b7611405a1b0"),
                            Alpha2Code = "RW",
                            Alpha3Code = "RWA",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("76e26eff-cf3f-4d6e-aae6-cf3f6a9f5ca7"),
                            Alpha2Code = "RE",
                            Alpha3Code = "REU",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = new Guid("488cc064-6271-425c-8562-c769da4c68e5"),
                            Alpha2Code = "BL",
                            Alpha3Code = "BLM",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = new Guid("150d6279-6736-4a3b-aed7-86e1b23ca6b1"),
                            Alpha2Code = "SH",
                            Alpha3Code = "SHN",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = new Guid("4e028214-1302-46c5-bce5-6ac6d7d8f550"),
                            Alpha2Code = "KN",
                            Alpha3Code = "KNA",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("92a7681e-ccc7-4930-9e47-edb3d9f4e9cd"),
                            Alpha2Code = "LC",
                            Alpha3Code = "LCA",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("2f861285-ae1c-48d8-8edb-e1952d86ca80"),
                            Alpha2Code = "MF",
                            Alpha3Code = "MAF",
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = new Guid("b937694b-9236-44d6-bec4-ee8883314aa3"),
                            Alpha2Code = "PM",
                            Alpha3Code = "SPM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = new Guid("2780f1a7-9056-4a52-9522-71b40442d886"),
                            Alpha2Code = "VC",
                            Alpha3Code = "VCT",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("44ae2342-0fb8-4510-9963-cced7b8def4a"),
                            Alpha2Code = "WS",
                            Alpha3Code = "WSM",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("36f57ced-cd3d-4763-bc60-932d6946b13c"),
                            Alpha2Code = "SM",
                            Alpha3Code = "SMR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("7462207c-12ae-42dc-bc3e-8e0bab3cf727"),
                            Alpha2Code = "ST",
                            Alpha3Code = "STP",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("2fc41f33-eb67-4470-81e3-116ac2769304"),
                            Alpha2Code = "SA",
                            Alpha3Code = "SAU",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("43164f4e-e476-4a39-a5ee-e53bf23c6fea"),
                            Alpha2Code = "SN",
                            Alpha3Code = "SEN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("60ef64ed-5cb7-4b8e-98ad-ea9fb27486a4"),
                            Alpha2Code = "RS",
                            Alpha3Code = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("50444744-61c8-4a96-8747-fe03e962eb9d"),
                            Alpha2Code = "SC",
                            Alpha3Code = "SYC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("e1afe3c2-28ca-4078-bfe4-97064bb50719"),
                            Alpha2Code = "SL",
                            Alpha3Code = "SLE",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("494e855f-e3da-48f1-b40c-e45fc8e728dc"),
                            Alpha2Code = "SG",
                            Alpha3Code = "SGP",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("f9fddddc-eead-4de8-b4bf-cf210c77f61c"),
                            Alpha2Code = "SX",
                            Alpha3Code = "SXM",
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = new Guid("9a1a90f6-40fb-4a25-ab5a-2b044e587605"),
                            Alpha2Code = "SK",
                            Alpha3Code = "SVK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("bcd6b8f0-38b7-4310-a532-920eb5543097"),
                            Alpha2Code = "SI",
                            Alpha3Code = "SVN",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("f71dd500-b6ae-44f8-805c-ab00d359753b"),
                            Alpha2Code = "SB",
                            Alpha3Code = "SLB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("35fcf832-8028-437a-9ac1-e080cddf275d"),
                            Alpha2Code = "SO",
                            Alpha3Code = "SOM",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("6f096c2e-10d6-465f-8bb6-f3ca476faa63"),
                            Alpha2Code = "ZA",
                            Alpha3Code = "ZAF",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("a8e34c5a-90bc-4df4-a6b7-de7f4d211125"),
                            Alpha2Code = "GS",
                            Alpha3Code = "SGS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = new Guid("9657dc08-d803-449f-8499-ab2a93267f0c"),
                            Alpha2Code = "SS",
                            Alpha3Code = "SSD",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("02e931e6-055a-4e65-aa24-e836881d3f60"),
                            Alpha2Code = "ES",
                            Alpha3Code = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("1a1ed865-82ce-4090-8b0b-33a28108f2dc"),
                            Alpha2Code = "LK",
                            Alpha3Code = "LKA",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("01eb164b-3f0f-4e77-aa7e-a42749f63c75"),
                            Alpha2Code = "SD",
                            Alpha3Code = "SDN",
                            Name = "Sudan (the)"
                        },
                        new
                        {
                            Id = new Guid("b7428613-0879-4421-b15b-a438d5c50054"),
                            Alpha2Code = "SR",
                            Alpha3Code = "SUR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("98d9e46d-66c1-4f44-94f6-fb2e90b8b300"),
                            Alpha2Code = "SJ",
                            Alpha3Code = "SJM",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = new Guid("e0a1bbb7-6460-42fb-9492-9344f548c773"),
                            Alpha2Code = "SE",
                            Alpha3Code = "SWE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("9bc1f1a9-7696-42e4-89aa-c93800704582"),
                            Alpha2Code = "CH",
                            Alpha3Code = "CHE",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("32617962-b412-4366-b0ea-c55f0dfc9af6"),
                            Alpha2Code = "SY",
                            Alpha3Code = "SYR",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = new Guid("4b88870d-f147-4d55-ba6b-cf470738f945"),
                            Alpha2Code = "TW",
                            Alpha3Code = "TWN",
                            Name = "Taiwan (Province of China)"
                        },
                        new
                        {
                            Id = new Guid("aa6c7744-f7ce-442b-aab3-cee4faa9f50b"),
                            Alpha2Code = "TJ",
                            Alpha3Code = "TJK",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("3e7dc4b7-a517-454c-8657-0e4a2df9e67c"),
                            Alpha2Code = "TZ",
                            Alpha3Code = "TZA",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = new Guid("a7ce5d31-a001-42ea-a5c9-9611d677df65"),
                            Alpha2Code = "TH",
                            Alpha3Code = "THA",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("cad06768-0005-464d-885e-d287cdb34e5d"),
                            Alpha2Code = "TL",
                            Alpha3Code = "TLS",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("fc1d5164-4161-4248-a795-eee401895cac"),
                            Alpha2Code = "TG",
                            Alpha3Code = "TGO",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("0311f6ff-5ace-4c2d-a769-73dddfbc08ed"),
                            Alpha2Code = "TK",
                            Alpha3Code = "TKL",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = new Guid("ad8f3577-f710-48be-a8ce-283082cdfd5c"),
                            Alpha2Code = "TO",
                            Alpha3Code = "TON",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("4ddde8d8-f7c8-48da-96a9-7e2a10cf9ef8"),
                            Alpha2Code = "TT",
                            Alpha3Code = "TTO",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("1da6a677-dcf9-40fe-afd6-c39b35e9d529"),
                            Alpha2Code = "TN",
                            Alpha3Code = "TUN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("dea3d7d2-2c87-433f-8c82-3f3fc094325e"),
                            Alpha2Code = "TR",
                            Alpha3Code = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("f13ed7e7-1d76-467b-8e68-a5612cbaa169"),
                            Alpha2Code = "TM",
                            Alpha3Code = "TKM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("10a74150-281e-41a3-a719-009854ccb354"),
                            Alpha2Code = "TC",
                            Alpha3Code = "TCA",
                            Name = "Turks and Caicos Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("333fdc8c-9bc7-4769-91c7-4f02726637c4"),
                            Alpha2Code = "TV",
                            Alpha3Code = "TUV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("7514bcc3-7881-4fb1-bc8f-c346d44fb58f"),
                            Alpha2Code = "UG",
                            Alpha3Code = "UGA",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("0663734e-c1d4-4a58-9c64-bb8463c82fbf"),
                            Alpha2Code = "UA",
                            Alpha3Code = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("c1badf50-9f25-4e84-a3e0-69e9fa545984"),
                            Alpha2Code = "AE",
                            Alpha3Code = "ARE",
                            Name = "United Arab Emirates (the)"
                        },
                        new
                        {
                            Id = new Guid("b3188d20-7572-4879-9f12-44ea7c06745c"),
                            Alpha2Code = "GB",
                            Alpha3Code = "GBR",
                            Name = "United Kingdom of Great Britain and Northern Ireland (the)"
                        },
                        new
                        {
                            Id = new Guid("e69d03f7-a99d-4c6c-b392-ce217b1dc868"),
                            Alpha2Code = "UM",
                            Alpha3Code = "UMI",
                            Name = "United States Minor Outlying Islands (the)"
                        },
                        new
                        {
                            Id = new Guid("014f2bc5-6ec6-483d-abcf-3ad3c10e0c71"),
                            Alpha2Code = "US",
                            Alpha3Code = "USA",
                            Name = "United States of America (the)"
                        },
                        new
                        {
                            Id = new Guid("86b175ea-352f-4437-87dd-7a64ab0a9a57"),
                            Alpha2Code = "UY",
                            Alpha3Code = "URY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("e00e2f21-a661-4e32-abf8-9c593cc62a4c"),
                            Alpha2Code = "UZ",
                            Alpha3Code = "UZB",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("fea13ee2-a1fe-473d-97db-117027425402"),
                            Alpha2Code = "VU",
                            Alpha3Code = "VUT",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("4f8d0d0e-c5b0-4990-ac31-d80d8099e84b"),
                            Alpha2Code = "VE",
                            Alpha3Code = "VEN",
                            Name = "Venezuela (Bolivarian Republic of)"
                        },
                        new
                        {
                            Id = new Guid("4fab2d4b-44f1-4d5c-9072-5aed6b58f5d1"),
                            Alpha2Code = "VN",
                            Alpha3Code = "VNM",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = new Guid("36e874da-595b-4f43-b6ed-9baf25abe8d9"),
                            Alpha2Code = "VG",
                            Alpha3Code = "VGB",
                            Name = "Virgin Islands (British)"
                        },
                        new
                        {
                            Id = new Guid("3a02147b-7946-4b6b-9456-462ca47f11e6"),
                            Alpha2Code = "VI",
                            Alpha3Code = "VIR",
                            Name = "Virgin Islands (U.S.)"
                        },
                        new
                        {
                            Id = new Guid("4fb924e5-d1fb-40c7-9b48-a40441ecf3b2"),
                            Alpha2Code = "WF",
                            Alpha3Code = "WLF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = new Guid("009dfcfd-7e30-4bf8-a10b-bd7b0a476651"),
                            Alpha2Code = "EH",
                            Alpha3Code = "ESH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = new Guid("c683f637-ddff-4238-9a1f-5ad10eeb36d9"),
                            Alpha2Code = "YE",
                            Alpha3Code = "YEM",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("99abee71-db3e-4909-b4b6-c47e1b2ec49b"),
                            Alpha2Code = "ZM",
                            Alpha3Code = "ZMB",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("50aa4ab0-3c14-4550-a87f-bdfca7d90638"),
                            Alpha2Code = "ZW",
                            Alpha3Code = "ZWE",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = new Guid("bb38feee-4d81-4f56-a11b-673ca15a95a0"),
                            Alpha2Code = "AX",
                            Alpha3Code = "ALA",
                            Name = "Åland Islands"
                        });
                });

            modelBuilder.Entity("MosqueLife.Server.Data.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("MemberSince")
                        .HasColumnType("date");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid");

                    b.Property<string>("StreetLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StreetLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.SubscriptionPaid", b =>
                {
                    b.Property<Guid>("MemeberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("MemeberId", "Year", "Month");

                    b.HasIndex("MemberId");

                    b.ToTable("SubscriptionPaid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosqueLife.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MosqueLife.Server.Data.Member", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.Payment", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.State", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.SubscriptionPaid", b =>
                {
                    b.HasOne("MosqueLife.Server.Data.Member", null)
                        .WithMany("SubscriptionsPaid")
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("MosqueLife.Server.Data.Member", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SubscriptionsPaid");
                });
#pragma warning restore 612, 618
        }
    }
}
